<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>FrameCtrl2.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="FrameCtrl2.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.9.6" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" />
  </ItemGroup>

</Project>